In [2]:
import numpy as np

# 1. Данные (2 признака, 5 наблюдений)
X = np.array([
    [2.5, 2.4],
    [0.5, 0.7],
    [2.2, 2.9],
    [1.9, 2.2],
    [3.1, 3.0]
])

# 2. Центрирование (отнимаем среднее по каждому признаку)
X_mean = np.mean(X, axis=0)
X_centered = X - X_mean

# 3. Матрица ковариации
cov_matrix = np.cov(X_centered.T)

# 4. Собственные значения и векторы
eig_vals, eig_vecs = np.linalg.eig(cov_matrix)

# 5. Сортировка по убыванию дисперсии (собственных значений)
sorted_idx = np.argsort(eig_vals)[::-1]
eig_vals = eig_vals[sorted_idx]
eig_vecs = eig_vecs[:, sorted_idx]

# 6. Выбор главных компонент (например, только первая)
principal_component = eig_vecs[:, 0:1]  # форма (2,1)


# 7. Проекция данных на новое пространство
X_projected = X_centered @ principal_component

# Вывод
print("Компоненты :\n", principal_component)
print("Исходные данные (центрированные):\n", X_centered)
print("\nСобственные векторы:\n", eig_vecs)
print("\nПроекция на первую компоненту:\n", X_projected)


Компоненты :
 [[0.72474155]
 [0.68902082]]
Исходные данные (центрированные):
 [[ 0.46  0.16]
 [-1.54 -1.54]
 [ 0.16  0.66]
 [-0.14 -0.04]
 [ 1.06  0.76]]

Собственные векторы:
 [[ 0.72474155 -0.68902082]
 [ 0.68902082  0.72474155]]

Проекция на первую компоненту:
 [[ 0.44362444]
 [-2.17719404]
 [ 0.57071239]
 [-0.12902465]
 [ 1.29188186]]


In [4]:
from sklearn.datasets import make_regression
from sklearn.decomposition import PCA

In [3]:
X, y = make_regression(n_samples=10, n_features=4, n_targets=1)
print(X, y)

[[-0.08391331  1.01628581  0.87074468 -0.87272104]
 [-1.62327836 -1.04446893  1.63445661  0.93815631]
 [ 0.43610983 -1.46426405  0.53829397  0.21622277]
 [-0.53497034 -0.32388599  0.53883882  2.12472764]
 [ 1.05647882 -1.64750669  0.37757904 -1.37938191]
 [-0.08782778 -0.5425538   0.58770538 -0.35743008]
 [-0.80093678 -1.29822834  0.87172127 -0.53596334]
 [-1.02116718  2.05962442 -0.12386312 -1.47273225]
 [ 0.25265761 -0.97006409 -0.0903515  -1.13650014]
 [ 0.94960908  1.086614    1.06742859 -0.23435876]] [ 115.40075002  -89.10831386  -66.50817793   10.84186857  -84.36235509
  -28.63832442 -131.10267359   77.35559537  -98.66698001  214.91283853]


In [5]:

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

print(X_pca)

[[ 1.37718444 -0.33355763]
 [-1.54770044 -1.33252039]
 [-1.14404088  0.61446696]
 [-1.36695318 -1.72734076]
 [-0.32390357  2.09192439]
 [-0.12639755  0.21553104]
 [-0.73926686  0.31736875]
 [ 2.64480891 -0.80188471]
 [ 0.1008054   1.24614366]
 [ 1.12546373 -0.29013131]]
